# -*- coding: utf-8 -*-
"""Poc_check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1ZYkGdqoCh9X21Ecm2x7eg_0Bz3YWJD
"""

import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

# Load the saved model
model = tf.keras.models.load_model('binary_classification_model.h5')

# Function to preprocess the uploaded image
def preprocess_image(image, target_size=(224, 224)):
    image = image.convert('RGB')
    image = image.resize(target_size)
    image = np.array(image) / 255.0  # Normalize to [0, 1]
    image = np.expand_dims(image, axis=0)  # Add batch dimension
    return image

# Streamlit app title
st.title("Image Classification with CNN")

# File uploader for the image
uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Load the image
    image = Image.open(uploaded_file)

    # Display the image
    st.image(image, caption='Uploaded Image', use_column_width=True)

    # Preprocess the image
    processed_image = preprocess_image(image)

    # Predict using the model
    prediction = model.predict(processed_image)

    # Display the prediction
    st.write(f"Prediction: {'Class 1' if prediction[0][0] > 0.5 else 'Class 0'}")
    st.write(f"Confidence: {prediction[0][0]:.2f}")